# ---- Build Stage ----
# This stage installs all dependencies (dev included) and builds the app
FROM node:20-alpine AS builder
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install all dependencies to run the build
RUN npm install

# Copy the rest of your app's source code
COPY . .


RUN npx tsc --project tsconfig.build.json

# ---- Production Stage ----
# This stage creates the final, lean image
FROM node:20-alpine
WORKDIR /usr/src/app

# Copy package files again to install only production dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy the built application from the 'builder' stage
COPY --from=builder /usr/src/app/dist ./dist

# The command to run your app
CMD ["node", "dist/main.js"]