services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs_app_prod
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: postgres_db_prod
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cf_tunnel_prod
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /srv/bible_memorization/cloudflared:/etc/cloudflared:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db_data_prod:
